#!/usr/bin/env bash
# cript that transfers a file from our client to a server
#Accepts 4 parameters
#1. The path to the file to be transferred
#2. The IP of the server we want to transfer the file to
#3. The username scp connects with
#4. The path to the SSH private key that scp uses

#if less than 4 args are passed
if (( $# < 4)); then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/

