#!/usr/bin/env bash
#Installs nginx listening on port 80
#configures it to return a page with the string "Hello World!" when quering Nginx at its root

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
service start nginx

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
