#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start

sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sh -c 'echo "Ceci n'\''est pas une page" > /var/www/html/404.html'

search_string="listen \[::\]:80 default_server;"
# replace_string="rewrite ^/redirect_me/(.*)$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent; }\n\n"
sudo sed -i "/$search_string/a \	location /redirect_me {\n\t\t return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n\t error_page 404 /404.html;\n\tlocation = /404.html {\n\t\t internal;\n\t}" /etc/nginx/sites-enabled/default


sudo /etc/init.d/nginx restart
