#!/usr/bin/env bash
#Installs and configure HAproxy on your lb-01 load balancer server.

sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.7 -y
sudo apt-get install -y haproxy=2.7.\*

#configuring HAproxy

sudo cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg

frontend ALX_load_balancer
	bind *:80
	default_backend ALX_web_servers

backend ALX_web_servers
	mode http
	balance roundrobin
	server 155255-web-01 34.229.136.156:80 check
	server 155255-web-02 54.85.214.9:80 check
EOF

sudo service haproxy restart
