#!/usr/bin/env bash
# configures Nginx to be running, and listening on port 80 of all the server’s active IPv4 IPs

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Start the Nginx service

sudo service nginx restart
