#!/usr/bin/env bash
# configures Nginx to be running, and listening on port 80 of all the server’s active IPv4 IPs

# Stop the Nginx service
sudo service nginx stop

# Modify the "listen" directives in the configuration file
sudo sed -i 's/listen 8080 default_server;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server ipv6only=on;/g' /etc/nginx/sites-enabled/default

# Start the Nginx service

sudo service nginx restart
