#!/usr/bin/env bash
#script that kills the process 7-highlander
echo $$ > /var/run/myscript.pid
while true;
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/myscript.pid, exit (1)' SIGQUIT SIGTERM
done
