#!/usr/bin/env bash
#that manages manage_my_process with either start, stop or restart command
args=("start" "stop" "restart")
if [[ $# -ne 1 ]] || ! [[ "${args[*]}" =~ $1 ]];
then
	echo "Usage: manage_my_process {start|stop|restart}"
fi
if [ "$1" == "start" ];
then
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ];
then
	pkill -f ./manage_my_process
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ];
then
	pkill -f ./manage_my_process &
	sudo rm /var/run/my_process.pid &
	sudo ./manage_my_process &
	echo $$ > /var/run/my_process.pid &
	echo "manage_my_process restarted"
fi
