#!/usr/bin/env bash
#script that displays Best School 10 times
n=0
while ((n<10));
do
	if ((n == 3));
	then
		echo "bad luck"
	elif ((n == 7));
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
