#!/usr/bin/env bash
#configures a server such that nginx must be running as nginx user and be listening on all active IPs on port 8080

sudo service nginx stop

sudo chmod 644 /etc/nginx/nginx.conf

sed -i "s/^#user\s.*/user nginx;/" /etc/nginx/nginx.conf

sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default

pkill apache2

sudo /etc/init.d/nginx start
