#!/usr/bin/env bash
# script that restarts gunicorn service gracefully

sudo systemctl reload gunicorn

sudo systemctl status gunicorn |  sed -n 's/.*Main PID: \(.*\)$/\1/g p' | cut -f1 -d' ' | xargs kill -HUP
